spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3307/reactive_board?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  profiles:
    include: security

logging:
  level:
    org.springframework.r2dbc.core: debug
